djangotcc/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('moodle.urls')),
]

moodle/urls.py
from django.urls import path

from .view import site
from .view import login

app_name = 'moodle'
urlpatterns = [
    path('',site.index, name='index'),
    path('sobre', site.sobre, name='sobre'),
    path('termos', site.termos, name='termos'),
    path('privacidade', site.privacidade, name='privacidade'),

    path('login', login.login, name='login'),
    path('cadastro', login.cadastro, name='cadastro'),
]

moodle/models.py
from django.db import models

# Create your models here.
class Usuario(models.Model):
    """docstring for Usuario."""

    id_usuario  = models.IntegerField(primary_key=True)

    nome        = models.CharField(max_length=100)
    sobrenome   = models.CharField(max_length=100)
    email       = models.CharField(max_length=100)
    senha       = models.CharField(max_length=200)

    descricao     = models.TextField()
    imagem_perfil = models.CharField(max_length=200)

    def __str__(self):
        return '{} {}'.format(self.nome, self.sobrenome)

moodle/templates/login/cadastro.html
{% extends 'login/estrutura/base.html'%}

{% block content %}
<form class='login100-form validate-form flex-sb flex-w' method="POST" action="{[ route('register') ]}">
  {% csrf_token %}

  <h2 class="login100-form-title p-b-5">
    Criar conta
  </h2>

  <div class="p-t-10 p-b-9">
    <span class="txt1">
      Nome
    </span>
  </div>

  <div class="wrap-input100 validate-input" data-validate = "Username is required">
    <input id="name" type="text" class="input100 form-control @error('name') is-invalid @enderror" name="name" value="{[ old('name') ]}" required autocomplete="name" autofocus>

    @error('name')
        <span class="invalid-feedback" role="alert">
            <strong>{[ $message ]}</strong>
        </span>
    @enderror

  </div>

  <div class="p-t-10 p-b-9">
    <span class="txt1">
      E-mail
    </span>
  </div>

  <div class="wrap-input100 validate-input" data-validate = "Username is required">
    <input id="email" type="email" class="input100 form-control @error('email') is-invalid @enderror " name="email" value="{[ old('email') ]}" required autocomplete="email" autofocus>

    @error('email')
    <span class="invalid-feedback mt-2 mb-0" role="alert">
      <strong>{[$message]}  </strong>
    </span>
    @enderror

  </div>

  <div class="container-fluid">
    <div class="row d-flex justify-content-between">
      <div class="col-md-6 col-sm-12 p-l-0 pr-s-0 pr-2">
        <div class="p-t-13 p-b-9">
          <span class="txt1">
            Senha
          </span>

        </div>
        <div class="wrap-input100 validate-input" data-validate = "Password is required">
          <input id="password" type="password" class="input100 rwidth form-control @error('password') is-invalid @enderror" name="password" required autocomplete="current-password">

          @error('password')
          <span class="invalid-feedback" role="alert">
            <strong>{[ $message ]}</strong>
          </span>
          @enderror

          <span class="focus-input100"></span>
        </div>
      </div>

      <div class="col-md-6 col-sm-12 p-l-0 p-r-0">
        <div class="p-t-13 p-b-9">
          <span class="txt1">
            Confirmar senha
          </span>

        </div>
        <div class="wrap-input100 validate-input" data-validate = "Password is required">
          <input type="password" class="input100 rwidth form-control @error('password') is-invalid @enderror" name="password_confirmation" required autocomplete="new-password">

          <span class="focus-input100"></span>
        </div>
      </div>
    </div>
  </div>


  <div class="container-login100-form-btn m-t-17">
    <button class="login100-form-btn">
      Acessar
    </button>
  </div>

  <div class="w-full text-center p-t-20">
    <a href="{% url 'moodle:login'%}" class="txt2 bo1">
      <i class="fas fa-chevron-left mr-1"></i>
      Voltar ao acesso
    </a>
  </div>

</form>
{% endblock content %}

moodle/templates/login/estrutura/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
	<title>{{APP_NAME}}</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="images/icons/favicon.ico"/>
<!--===============================================================================================-->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

<link href="" rel="stylesheet">
<link href="" rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/login/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/login/main.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/site/landing-page.css' %}">
<!--===============================================================================================-->
</head>
<body>
  {% include "site/estrutura/header.html" %}

	<div class="limiter" style="background-image: url('{% static 'img/polygonal_background.jpg' %}')">
		<div class="container-login100" >
			<div class="wrap-login100 p-l-45 p-r-45 p-t-35 p-b-25">
        {% block content %} {% endblock content %}
			</div>
		</div>
	</div>
	  {% include "site/estrutura/footer.html" %}
</body>
</html>

moodle/templates/login/login.html
{% extends 'login/estrutura/base.html'%}


{% block content %}

<form class="login100-form validate-form flex-sb flex-w" method="POST" action="{[ route('login') ]}">
  {% csrf_token %}
  <h2 class="login100-form-title p-b-5">
    Acesso
  </h2>

  <div class="p-t-10 p-b-9">
    <span class="txt1">
      E-mail
    </span>
  </div>

  <div class="wrap-input100 validate-input" data-validate = "Username is required">
    <input id="email" type="email" class="input100 form-control @error('email') is-invalid @enderror " name="email" value="{[ old('email') ]}" required autocomplete="email" autofocus>

    @error('email')
    <span class="invalid-feedback mt-2 mb-0" role="alert">
      <strong>{[$message]}  </strong>
    </span>
    @enderror

  </div>

  <div class="p-t-13 p-b-9">
    <span class="txt1">
      Senha
    </span>

    <a href="{[ route('password.request') ]}" class="txt2 bo1 m-l-5">
      (Esqueceu sua senha?)
    </a>
  </div>
  <div class="wrap-input100 validate-input" data-validate = "Password is required">
    <input id="password" type="password" class="input100 form-control @error('password') is-invalid @enderror" name="password" required autocomplete="current-password">

    @error('password')
        <span class="invalid-feedback" role="alert">
            <strong>{[ $message ]}</strong>
        </span>
    @enderror

    <span class="focus-input100"></span>
  </div>
  <div class="p-t-13 p-b-9 d-flex align-items-center">
    <input class="mr-2" type="checkbox" name="remember" id="remember" {[ old('remember') ? 'checked' : '' ]}>
    <label for="remember">Manter-me conectado</label>
  </div>


  <div class="container-login100-form-btn m-t-17">
    <button class="login100-form-btn">
      Acessar
    </button>
  </div>

  <div class="w-full text-center p-t-20">
    <a href="{% url 'moodle:cadastro' %}" class="txt2 bo1">
      Criar uma conta gratuita
    </a>
  </div>

  <!-- <hr class="col-12">
  <span class="login100-form-title p-b-30">
    Sign In With
  </span>
  <a href="#" class="btn-face m-b-20">
    <i class="fab fa-facebook-square"></i>
    Facebook
  </a>
  <a href="#" class="btn-google m-b-20">
    <img src="{[asset('img/icon/icon-google.png')]}" alt="GOOGLE">
    Google
  </a> -->

</form>

{% endblock content %}

moodle/templates/site/estrutura/footer.html
<!-- Footer -->
<footer class="footer bg-light">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 h-100 text-center text-lg-left my-auto">
          <ul class="list-inline mb-2">
            <li class="list-inline-item">
              <a href="{% url 'moodle:sobre' %}">Sobre</a>
            </li>
            <li class="list-inline-item">&sdot;</li>
            <li class="list-inline-item">
              <a href="{%url 'moodle:termos' %}">Termos de uso</a>
            </li>
            <li class="list-inline-item">&sdot;</li>
            <li class="list-inline-item">
              <a href="{%url 'moodle:privacidade' %}">Politica de privacidade</a>
            </li>
          </ul>
          <p class="text-muted small mb-4 mb-lg-0">&copy; IFSP - TSI 2022. All Rights Reserved.</p>
        </div>

      </div>
    </div>

  </footer>

moodle/templates/site/estrutura/header.html
<nav class="navbar navbar-light bg-light static-top">
    <div class="container-fluid">
      <a class="navbar-brand" href="">{{APP_NAME}}</a>

        <a class="btn btn-primary" href="{%url 'moodle:login' %}">Log in</a>

    </div>
  </nav>

moodle/templates/site/estrutura/institucional.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>{{APP_NAME}} - {{title}}</title>

  <!-- Bootstrap core CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">


  <!-- Custom fonts for this template -->
  <link href="" rel="stylesheet">
  <link href="" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/site/landing-page.css' %}" rel="stylesheet">
  <link href="{% static 'css/site/blog-home.css' %}" rel="stylesheet">

</head>

<body>
  <!-- Navigation -->
  {% include "site/estrutura/header.html" %}

  <!-- Masthead -->
  <header class="text-white text-center">
    <div class="overlay bg-gradient-home" ></div>
    <div class="container-fluid" style="background-image: url('{% static 'images/site/polygonal_background.jpg' %}')">
      <div class="row bg-gradient-institucional" >
        <div class="col-xl-9 mx-auto">
          <h1 class="p-5 font-weight-light">{{title}}</h1>
        </div>
      </div>
    </div>
  </header>

  <section>
    <div class="container">
      <div class="row">
        <div class="col-12">

            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="{%url 'moodle:index' %}">Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">{{title}}</li>
            </ol>

        </div>
      </div>
    </div>
  </section>

  <section class="m-5">
    <div class="container">
      <div class="row">

        <div class="col-md-4 mb-5">

          <div class="list-group">

            <a href="{%url 'moodle:sobre' %}" class="list-group-item list-group-item-action {{sobre|yesno:'active,,'}}">Sobre nós</a>
            <a href="{%url 'moodle:termos' %}" class="list-group-item list-group-item-action {{termos|yesno:'active,,'}}">Termos de uso</a>
            <a href="{%url 'moodle:privacidade' %}" class="list-group-item list-group-item-action {{privacidade|yesno:'active,,'}}">Politica de privacidade</a>

          </div>

        </div>

        <div class="col-md-8">
          {% block content %} {% endblock content %}
        </div>

      </div>
    </div>
  </section>

  {% include "site/estrutura/footer.html" %}

  <!-- Bootstrap core JavaScript -->
  <!-- Bootstrap core JavaScript -->
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>

</body>

</html>

moodle/templates/site/index.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>{{APP_NAME}}</title>

  <!-- Bootstrap core CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">


  <!-- Custom fonts for this template -->
  <link href="" rel="stylesheet">
  <link href="" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/site/landing-page.css' %}" rel="stylesheet">
  <link href="{% static 'css/site/blog-home.css' %}" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  {% include "site/estrutura/header.html" %}

  <!-- Masthead -->
  <header class="masthead text-white bg-gradient-home text-center">
    <div class="overlay" style="background-image: url('{% static 'images/site/polygonal_background.jpg' %}')"></div>
    <div class="container">
      <div class="row">
        <div class="col-xl-9 mx-auto">
          <h1 class="mb-5 font-weight-light">Encontre materiais</h1>
        </div>
        <div class="col-10 mx-auto">
          <form class="zindex-fixed">
            <div class="form-row row justify-content-center">
              <div class="col-7">
                <input type="text" class="form-control form-control-lg" placeholder="Pesquise por matéria, conteudo ou nivel">
                <span class="text-left pl-1">Ex: matematica regra de três fundamental</span>
              </div>
              <div class="col-1">
                <button type="submit" class="btn btn-block btn-lg btn-primary">Busque!</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </header>

  <!-- Icons Grid -->
  <section class="features-icons bg-light text-center">
    <div class="container">
      <div class="row">
        <div class="col-lg-4">
          <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
            <div class="features-icons-icon d-flex">
              <i class="fas fa-share-alt m-auto text-primary"></i>
            </div>
            <h3>Compartilhe conhecimento</h3>
            <p class="lead mb-0">Compartilhe seus materiais de aula com outros professores!</p>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
            <div class="features-icons-icon d-flex">
              <i class="far fa-lightbulb m-auto text-primary "></i>
            </div>
            <h3>Encontre ideias</h3>
            <p class="lead mb-0">Encontre novos materiais para aplicar em aula</p>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="features-icons-item mx-auto mb-0 mb-lg-3">
            <div class="features-icons-icon d-flex">
              <i class="fas fa-users m-auto text-primary"></i>
            </div>
            <h3>Contribua com a comunidade</h3>
            <p class="lead mb-0">Ajude nossa comunidade a crescer e levar educação ao país!</p>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- Image Showcases -->
  <section class="showcase">
    <div class="container-fluid">
      <div class="row no-gutters">

        <div class="col-lg-6 order-lg-2 text-white showcase-img" style="background-image: url('{% static 'images/site/share.jpeg' %}')"></div>
        <div class="col-lg-6 order-lg-1 my-auto showcase-text">
          <h2>Compartilhe conhecimento</h2>
          <p class="lead mb-0 text-justify">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas cursus ex id maximus condimentum. Duis sed porta risus, ut consectetur dolor. Sed id euismod libero. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae</p>
        </div>
      </div>
      <div class="row no-gutters">
        <div class="col-6 text-white showcase-img" style="background-image: url('{% static 'images/site/new_idea.jpg' %}')"></div>
        <div class="col-6 my-auto showcase-text">
          <h2>Encontre ideias</h2>
          <p class="lead mb-0 text-justify">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas cursus ex id maximus condimentum. Duis sed porta risus, ut consectetur dolor. Sed id euismod libero. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae</p>
        </div>
      </div>
      <div class="row no-gutters">
        <div class="col-6 order-lg-2 text-white showcase-img" style="background-image: url('{% static 'images/site/comunity.jpeg' %}')"></div>
        <div class="col-6 order-lg-1 my-auto showcase-text">
          <h2>Contribua com a comunidade</h2>
          <p class="lead mb-0 text-justify">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas cursus ex id maximus condimentum. Duis sed porta risus, ut consectetur dolor. Sed id euismod libero. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae</p>
        </div>
      </div>
    </div>
  </section>


  {% include "site/estrutura/footer.html" %}

  <!-- Bootstrap core JavaScript -->
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>


</body>

</html>

moodle/templates/site/privacidade.html
{% extends 'site/estrutura/institucional.html'%}

{%block content%}
  <section class="text-justify">

    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ullamcorper et mauris eget gravida. Ut feugiat ut tortor vitae consequat. Mauris viverra augue eget mi vulputate feugiat. Aliquam cursus malesuada ex tincidunt tristique. Vivamus ut massa tincidunt, bibendum orci in, imperdiet justo. Morbi ut augue orci. Aenean eu justo ut leo tincidunt bibendum id nec dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Pellentesque quis tellus neque. Vivamus in metus et tortor elementum pharetra tempor at massa. Nulla ut blandit nulla. Integer blandit mi eget nibh rhoncus accumsan. Phasellus aliquet nulla mauris, auctor scelerisque erat imperdiet id.</p>

    <p>Maecenas id semper mauris, vitae tincidunt orci. Aliquam suscipit vehicula rutrum. Aliquam interdum nibh a mollis semper. Nulla laoreet urna tortor, quis gravida neque tempor sed. Sed quam nisl, viverra eget pellentesque id, interdum et sapien. Cras consectetur ante nunc, et aliquam erat mollis vel. Cras sit amet nisl commodo odio ullamcorper elementum eu vitae diam. Duis ut elementum neque, sed hendrerit lorem. Maecenas non turpis eget dolor vehicula dignissim posuere tristique odio.</p>

    <p> Donec at molestie erat, id porta dui. Nullam sed est et magna mattis ornare sed sagittis nunc. Donec sed volutpat tortor. Proin malesuada dictum libero, sit amet sagittis sapien. Ut sollicitudin nulla quis lorem facilisis, sodales ornare neque laoreet. Vivamus sit amet nisi auctor, tincidunt nulla a, lacinia mi. Aenean convallis dui nec orci laoreet, sed suscipit tellus tempor. Sed in fringilla dui. Vivamus sit amet dui eros. Donec lorem elit, lobortis eu nisl vitae, dignissim feugiat sem. Praesent accumsan luctus lacinia.</p>
  </section>

{%endblock content%}

moodle/templates/site/sobre.html
{% extends 'site/estrutura/institucional.html'%}

{%block content%}
  <section class="text-justify">

    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ullamcorper et mauris eget gravida. Ut feugiat ut tortor vitae consequat. Mauris viverra augue eget mi vulputate feugiat. Aliquam cursus malesuada ex tincidunt tristique. Vivamus ut massa tincidunt, bibendum orci in, imperdiet justo. Morbi ut augue orci. Aenean eu justo ut leo tincidunt bibendum id nec dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Pellentesque quis tellus neque. Vivamus in metus et tortor elementum pharetra tempor at massa. Nulla ut blandit nulla. Integer blandit mi eget nibh rhoncus accumsan. Phasellus aliquet nulla mauris, auctor scelerisque erat imperdiet id.</p>

    <p>Maecenas id semper mauris, vitae tincidunt orci. Aliquam suscipit vehicula rutrum. Aliquam interdum nibh a mollis semper. Nulla laoreet urna tortor, quis gravida neque tempor sed. Sed quam nisl, viverra eget pellentesque id, interdum et sapien. Cras consectetur ante nunc, et aliquam erat mollis vel. Cras sit amet nisl commodo odio ullamcorper elementum eu vitae diam. Duis ut elementum neque, sed hendrerit lorem. Maecenas non turpis eget dolor vehicula dignissim posuere tristique odio.</p>

    <p> Donec at molestie erat, id porta dui. Nullam sed est et magna mattis ornare sed sagittis nunc. Donec sed volutpat tortor. Proin malesuada dictum libero, sit amet sagittis sapien. Ut sollicitudin nulla quis lorem facilisis, sodales ornare neque laoreet. Vivamus sit amet nisi auctor, tincidunt nulla a, lacinia mi. Aenean convallis dui nec orci laoreet, sed suscipit tellus tempor. Sed in fringilla dui. Vivamus sit amet dui eros. Donec lorem elit, lobortis eu nisl vitae, dignissim feugiat sem. Praesent accumsan luctus lacinia.</p>
  </section>
  
{%endblock content%}

moodle/templates/site/termos.html
{% extends 'site/estrutura/institucional.html'%}

{%block content%}
  <section class="text-justify">

    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ullamcorper et mauris eget gravida. Ut feugiat ut tortor vitae consequat. Mauris viverra augue eget mi vulputate feugiat. Aliquam cursus malesuada ex tincidunt tristique. Vivamus ut massa tincidunt, bibendum orci in, imperdiet justo. Morbi ut augue orci. Aenean eu justo ut leo tincidunt bibendum id nec dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Pellentesque quis tellus neque. Vivamus in metus et tortor elementum pharetra tempor at massa. Nulla ut blandit nulla. Integer blandit mi eget nibh rhoncus accumsan. Phasellus aliquet nulla mauris, auctor scelerisque erat imperdiet id.</p>

    <p>Maecenas id semper mauris, vitae tincidunt orci. Aliquam suscipit vehicula rutrum. Aliquam interdum nibh a mollis semper. Nulla laoreet urna tortor, quis gravida neque tempor sed. Sed quam nisl, viverra eget pellentesque id, interdum et sapien. Cras consectetur ante nunc, et aliquam erat mollis vel. Cras sit amet nisl commodo odio ullamcorper elementum eu vitae diam. Duis ut elementum neque, sed hendrerit lorem. Maecenas non turpis eget dolor vehicula dignissim posuere tristique odio.</p>

    <p> Donec at molestie erat, id porta dui. Nullam sed est et magna mattis ornare sed sagittis nunc. Donec sed volutpat tortor. Proin malesuada dictum libero, sit amet sagittis sapien. Ut sollicitudin nulla quis lorem facilisis, sodales ornare neque laoreet. Vivamus sit amet nisi auctor, tincidunt nulla a, lacinia mi. Aenean convallis dui nec orci laoreet, sed suscipit tellus tempor. Sed in fringilla dui. Vivamus sit amet dui eros. Donec lorem elit, lobortis eu nisl vitae, dignissim feugiat sem. Praesent accumsan luctus lacinia.</p>
  </section>

{%endblock content%}